default:
	javac *.java
	javac peer_1001/*.java
	javac peer_1002/*.java
	javac peer_1003/*.java
	javac peer_1004/*.java
	javac peer_1005/*.java

clean:
	rm *.class
	rm peer_1001/*.class
	rm peer_1002/*.class
	rm peer_1003/*.class
	rm peer_1004/*.class
	rm peer_1005/*.class